name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-perf-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Simulate performance test
        run: |
          echo "read=0.2" > result.txt
          echo "write=0.1" >> result.txt
          echo "cycle=3" >> result.txt

      - name: Upload performance result
        uses: actions/upload-artifact@v4
        with:
          name: perf-results
          path: result.txt

