name: Comment on Performance

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  comment-perf:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Download artifact from CI
        uses: dawidd6/action-download-artifact@v3
        with:
          name: perf-results
          run_id: ${{ github.event.workflow_run.id }}
          path: ./perf-data

      - name: Read performance result
        id: perf
        run: |
          read=$(grep "read=" perf-data/result.txt | cut -d "=" -f2)
          write=$(grep "write=" perf-data/result.txt | cut -d "=" -f2)
          cycle=$(grep "cycle=" perf-data/result.txt | cut -d "=" -f2)
          echo "read=$read" >> $GITHUB_OUTPUT
          echo "write=$write" >> $GITHUB_OUTPUT
          echo "cycle=$cycle" >> $GITHUB_OUTPUT

      - name: Find related pull request
        id: find-pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commitSha = context.payload.workflow_run.head_sha;
            const { data: prs } = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commitSha,
            });
            if (prs.length === 0) {
              throw new Error(`No PR found for commit ${commitSha}`);
            }
            core.setOutput('pr_number', prs[0].number);

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          pr_number: ${{ steps.find-pr.outputs.pr_number }}
          message: |
            result :
            -  Read Miss : `${{ steps.perf.outputs.read }}`
            -  Write Miss : `${{ steps.perf.outputs.write }}`
            -  Cycles : `${{ steps.perf.outputs.cycle }}`

