name: Comment on CI failure

on:
  repository_dispatch:
    types: [ci-comment]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Post comment
        env:
          PR_NUMBER: ${{ github.event.client_payload.pr_number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Posting comment to PR #$PR_NUMBER"
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"🚨 CI failed due to performance regression.  Dylan push seems bad ...\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"

