# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      issues: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: catch-perf
        run: |
          file_prev="coucou"
          prev_cycle=$(cat $file_prev | grep "cycle" | cut -d "=" -f 2)
          prev_read=$(cat $file_prev | grep "read" | cut -d "=" -f 2)
          prev_write=$(cat $file_prev| grep "write" | cut -d "=" -f 2)
          nb_read_miss=0.2
          nb_write_miss=0.1
          nb_cycle_execution=3

          echo "read = $nb_read_miss write = $nb_write_miss  cycles = $nb_cycle_execution"
          echo "read_prev = $prev_read write_prev = $prev_write cycle = $prev_cycle"
          if (( $(echo "$nb_read_miss > $prev_read"  | bc -l) ))
          then
            echo -e  "\033[31mThe percentage of miss on read has grow\033[0m"
            echo "exitcode=1" >> $GITHUB_OUTPUT
            exit 1
          fi
          if (( $(echo "$nb_write_miss > $prev_write"  | bc -l) ))
          then
            echo -e  "\033[31mThe percentage of miss on write has grow\033[0m"
            echo "exitcode=2" >> $GITHUB_OUTPUT
            exit 2
          fi
          if (( $(echo "$nb_cycle_execution > $prev_cycle"  | bc -l) ))
          then
            echo -e  "\033[31mThe number of cycle has grow\033[0m"
            echo "exitcode=3" >> $GITHUB_OUTPUT
            exit 3
          fi

      - name: Change best perf
        id: new_best_perf
        run: |
          file_prev="coucou"
          prev_cycle=$(cat $file_prev | grep "cycle" | cut -d "=" -f 2)
          prev_read=$(cat $file_prev | grep "read" | cut -d "=" -f 2)
          prev_write=$(cat $file_prev| grep "write" | cut -d "=" -f 2)
          nb_read_miss=0.0
          nb_write_miss=0.0
          nb_cycle_execution=1

          echo "read = $nb_read_miss write = $nb_write_miss  cycles = $nb_cycle_execution"
          echo "read_prev = $prev_read write_prev = $prev_write cycle = $prev_cycle"
          x=""
          if (( $(echo "$nb_read_miss < $prev_read"  | bc -l) ))
          then
            x+=" read=$nb_read_miss"
          fi
          if (( $(echo "$nb_write_miss < $prev_write"  | bc -l) ))
          then
            x+=" write=$nb_write_miss"
          fi
          if (( $(echo "$nb_cycle_execution < $prev_cycle"  | bc -l) ))
          then
            x+=" cycle=$nb_cycle_execution"
          fi
          if [[ $x != "" ]]
          then
            echo "message=$x" >> $GITHUB_OUTPUT
          fi

      - name: Trigger comment workflow better 
        uses: thollander/actions-comment-pull-request@v3
        if: steps.new_best_perf.outputs.message != ''
        with:
          message: >
            ${{
              steps.new_best_perf.outputs.message 
            }}

      - name: Trigger comment workflow bad 
        if: failure() && steps.catch-perf.outputs.exitcode != '0'
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: >
            ${{
              steps.catch-perf.outputs.exitcode == '1' && 'Pipeline has failed due to a decrease in performance in read' ||
              steps.catch-perf.outputs.exitcode == '2' && 'Pipeline has failed due to a decrease in performance in write' ||
              steps.catch-perf.outputs.exitcode == '3' && 'Pipeline has failed due to an increase for number of cycle' ||
             'Unknow error code'
            }}

